import type { PropertyUpsertInput } from '@/lib/properties/types'

function imageSet(base: string) {
  return [
    `${base}?auto=format&fit=crop&w=1600&q=80`,
    `${base}?auto=format&fit=crop&w=1400&q=80`,
    `${base}?auto=format&fit=crop&w=1200&q=80`,
    `${base}?auto=format&fit=crop&w=1000&q=80`,
  ]
}

export const seededProperties: PropertyUpsertInput[] = [
  {
    title: 'Contemporary Lekki Villa',
    location: 'Lekki Phase 1, Lagos',
    fullAddress: '12 Admiralty Way, Lekki Phase 1, Lagos',
    estate: 'Admiralty Estate',
    latitude: 6.4474,
    longitude: 3.4722,
    priceValue: 450000000,
    currency: 'NGN',
    pricingPeriod: 'sale',
    type: 'For Sale',
    listedBy: 'Agent',
    bedrooms: 5,
    bathrooms: 5,
    features: ['Swimming pool', 'BQ', '24/7 power', 'Cinema room'],
    imageUrls: imageSet('https://images.unsplash.com/photo-1600585154526-990dced4db0d'),
    videoUrl: 'https://example.com/videos/lekki-villa-neighbourhood.mp4',
    referenceCode: 'ULO-SEED-001',
    documentInfo: 'Governor consent available',
    contactName: 'Adeyemi Cole',
    contactPhone: '+2348010000001',
    contactEmail: 'lekkivilla@ulo.com',
    verificationStatus: 'verified',
    disclaimerAccepted: true,
    description: 'A newly built premium villa in Lekki with generous living spaces and high-end finishing.',
    status: 'active',
    featured: true,
  },
  {
    title: 'Ikoyi Waterfront Apartment',
    location: 'Ikoyi, Lagos',
    fullAddress: '18 Bourdillon Road, Ikoyi, Lagos',
    estate: 'Bourdillon Court',
    latitude: 6.4549,
    longitude: 3.4338,
    priceValue: 28000000,
    currency: 'NGN',
    pricingPeriod: 'monthly',
    type: 'For Rent',
    listedBy: 'Landlord',
    bedrooms: 3,
    bathrooms: 3,
    features: ['Waterfront view', 'Gym', 'Elevator', 'Smart access'],
    imageUrls: imageSet('https://images.unsplash.com/photo-1502672260266-1c1ef2d93688'),
    videoUrl: 'https://example.com/videos/ikoyi-waterfront-neighbourhood.mp4',
    referenceCode: 'ULO-SEED-002',
    documentInfo: 'Tenancy terms available on request',
    contactName: 'Tobi Balogun',
    contactPhone: '+2348010000002',
    contactEmail: 'ikoyiapartment@ulo.com',
    verificationStatus: 'requested',
    disclaimerAccepted: true,
    description: 'Refined waterfront living in Ikoyi with direct access to premium city infrastructure.',
    status: 'active',
    featured: true,
  },
  {
    title: 'Ibeju-Lekki Dry Land',
    location: 'Ibeju-Lekki, Lagos',
    fullAddress: 'Coastal Road Axis, Ibeju-Lekki, Lagos',
    estate: 'Atlantic Growth Corridor',
    latitude: 6.4683,
    longitude: 4.051,
    priceValue: 55000000,
    currency: 'NGN',
    pricingPeriod: 'sale',
    type: 'Land',
    listedBy: 'Owner',
    bedrooms: 0,
    bathrooms: 0,
    features: ['Dry land', 'Good road network', 'Fast developing axis', 'Survey available'],
    imageUrls: imageSet('https://images.unsplash.com/photo-1500382017468-9049fed747ef'),
    videoUrl: 'https://example.com/videos/ibeju-neighbourhood.mp4',
    referenceCode: 'ULO-SEED-004',
    documentInfo: 'Survey and deed of assignment available',
    contactName: 'Kehinde Ojo',
    contactPhone: '+2348010000004',
    contactEmail: 'ibejuland@ulo.com',
    verificationStatus: 'requested',
    disclaimerAccepted: true,
    description: 'Strategically positioned land parcel in the Ibeju-Lekki corridor with solid growth prospects.',
    status: 'active',
    featured: true,
  },
  {
    title: 'Victoria Island Shortlet Suite',
    location: 'Victoria Island, Lagos',
    fullAddress: '7 Akin Adesola Street, Victoria Island, Lagos',
    estate: 'Civic Towers Residences',
    latitude: 6.4281,
    longitude: 3.4219,
    priceValue: 450000,
    currency: 'NGN',
    pricingPeriod: 'per-day',
    type: 'Shortlet',
    listedBy: 'Agent',
    bedrooms: 2,
    bathrooms: 2,
    features: ['Fully furnished', 'Daily housekeeping', 'Fast Wi-Fi', 'Pool access'],
    imageUrls: imageSet('https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'),
    videoUrl: 'https://example.com/videos/vi-shortlet-neighbourhood.mp4',
    referenceCode: 'ULO-SEED-005',
    documentInfo: 'Managed shortlet inventory',
    contactName: 'Nneka James',
    contactPhone: '+2348010000005',
    contactEmail: 'vishortlet@ulo.com',
    verificationStatus: 'verified',
    disclaimerAccepted: true,
    description: 'A polished shortlet apartment in Victoria Island for corporate stays and city breaks.',
    status: 'active',
    featured: false,
  },
]
