export interface Room {
  id: string
  name: string
  description: string
  price: string
  priceValue: number
  maxGuests: number
  bedType: string
  size: string
  amenities: string[]
  images: string[]
  available: boolean
}

export interface Hotel {
  id: string
  name: string
  location: string
  description: string
  rating: number
  reviewCount: number
  price: string
  image: string
  images: string[]
  amenities: string[]
  rooms: Room[]
  contact: {
    phone: string
    email: string
    address: string
  }
}

export const hotels: Hotel[] = [
  {
    id: 'echelon-luxury-suites',
    name: 'Echelon Luxury Suites',
    location: 'Victoria Island, Lagos',
    description: 'Experience unparalleled luxury at Echelon Luxury Suites, where world-class amenities meet exceptional Nigerian hospitality. Our newly renovated suites offer breathtaking views of the Lagos skyline, perfect for business travelers and tourists seeking comfort and elegance.',
    rating: 4.8,
    reviewCount: 324,
    price: '₦85,000',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&h=800&fit=crop',
    ],
    amenities: [
      'Free WiFi',
      'Swimming Pool',
      'Spa & Wellness',
      'Fitness Center',
      'Restaurant & Bar',
      '24/7 Room Service',
      'Concierge',
      'Airport Shuttle',
      'Business Center',
      'Parking',
    ],
    contact: {
      phone: '+234 700 123 4567',
      email: 'reservations@echelonluxury.com',
      address: 'Plot 5, Victoria Island, Lagos',
    },
    rooms: [
      {
        id: 'deluxe-room',
        name: 'Deluxe Room',
        description: 'Spacious room with city view, king bed, and modern amenities.',
        price: '₦85,000',
        priceValue: 85000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '45 sqm',
        amenities: ['King Bed', 'City View', 'Mini Bar', 'Safe', 'TV', 'Air Conditioning', 'WiFi'],
        images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'executive-suite',
        name: 'Executive Suite',
        description: 'Luxurious suite with separate living area, panoramic views, and premium amenities.',
        price: '₦150,000',
        priceValue: 150000,
        maxGuests: 3,
        bedType: 'King Bed',
        size: '75 sqm',
        amenities: ['King Bed', 'Living Room', 'Panoramic View', 'Mini Bar', 'Safe', 'Smart TV', 'Jacuzzi', 'Butler Service'],
        images: ['https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'presidential-suite',
        name: 'Presidential Suite',
        description: 'The ultimate in luxury with private terrace, personal chef, and dedicated butler.',
        price: '₦350,000',
        priceValue: 350000,
        maxGuests: 4,
        bedType: 'King Bed',
        size: '150 sqm',
        amenities: ['Private Terrace', 'Personal Chef', 'Butler Service', 'Jacuzzi', 'Living Room', 'Dining Room', 'Panoramic View', 'Smart Home'],
        images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop'],
        available: true,
      },
    ],
  },
  {
    id: 'the-landmark-hotel',
    name: 'The Landmark Hotel',
    location: 'Ikoyi, Lagos',
    description: 'Nestled in the prestigious Ikoyi district, The Landmark Hotel offers a perfect blend of modern sophistication and timeless elegance. Enjoy our rooftop pool, world-class dining, and impeccable service.',
    rating: 4.9,
    reviewCount: 256,
    price: '₦120,000',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop',
    ],
    amenities: [
      'Free WiFi',
      'Rooftop Pool',
      'Fitness Center',
      'Fine Dining Restaurant',
      'Lounge Bar',
      'Spa',
      'Valet Parking',
      'Conference Rooms',
      'Beauty Salon',
      'Laundry Service',
    ],
    contact: {
      phone: '+234 700 234 5678',
      email: 'book@landmarkhotel.com',
      address: '45 Queen Elizabeth Way, Ikoyi, Lagos',
    },
    rooms: [
      {
        id: 'standard-room',
        name: 'Standard Room',
        description: 'Comfortable room with all essential amenities for a pleasant stay.',
        price: '₦120,000',
        priceValue: 120000,
        maxGuests: 2,
        bedType: 'Queen Bed',
        size: '35 sqm',
        amenities: ['Queen Bed', 'Work Desk', 'Mini Bar', 'Safe', 'Smart TV', 'Air Conditioning'],
        images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'deluxe-suite',
        name: 'Deluxe Suite',
        description: 'Spacious suite with separate living area and premium amenities.',
        price: '₦220,000',
        priceValue: 220000,
        maxGuests: 3,
        bedType: 'King Bed',
        size: '65 sqm',
        amenities: ['King Bed', 'Living Room', 'Mini Bar', 'Safe', 'Smart TV', 'Rain Shower', 'City View'],
        images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'royal-suite',
        name: 'Royal Suite',
        description: 'Experience royal treatment with our expansive suite featuring butler service.',
        price: '₦450,000',
        priceValue: 450000,
        maxGuests: 4,
        bedType: 'King Bed',
        size: '180 sqm',
        amenities: ['Private Balcony', 'Butler Service', 'Living Room', 'Dining Area', 'Jacuzzi', 'Personal Chef Option'],
        images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop'],
        available: true,
      },
    ],
  },
  {
    id: 'radisson-blu-ikeja',
    name: 'Radisson Blu Ikeja',
    location: 'Ikeja, Lagos',
    description: 'Located in the heart of Ikeja, Radisson Blu offers contemporary accommodation with easy access to shopping centers and the business district. Perfect for both leisure and business travelers.',
    rating: 4.6,
    reviewCount: 412,
    price: '₦95,000',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop',
    ],
    amenities: [
      'Free High-Speed WiFi',
      'Outdoor Pool',
      'Fitness Center',
      'Multiple Restaurants',
      'Lounge',
      'Business Center',
      'Meeting Rooms',
      'Currency Exchange',
      'Car Rental',
      '24/7 Reception',
    ],
    contact: {
      phone: '+234 700 345 6789',
      email: 'reservations.ikeja@radisson.com',
      address: '42/44 Isaac John Street, Ikeja, Lagos',
    },
    rooms: [
      {
        id: 'superior-room',
        name: 'Superior Room',
        description: 'Modern room with comfortable bedding and all necessary amenities.',
        price: '₦95,000',
        priceValue: 95000,
        maxGuests: 2,
        bedType: 'Queen Bed',
        size: '28 sqm',
        amenities: ['Queen Bed', 'Work Desk', 'Coffee Maker', 'Safe', 'Flat Screen TV'],
        images: ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'premium-room',
        name: 'Premium Room',
        description: 'Spacious room with premium amenities and city views.',
        price: '₦140,000',
        priceValue: 140000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '38 sqm',
        amenities: ['King Bed', 'City View', 'Mini Bar', 'Nespresso Machine', 'Bathrobes', 'Slippers'],
        images: ['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'business-suite',
        name: 'Business Suite',
        description: 'Suite designed for business travelers with dedicated workspace.',
        price: '₦250,000',
        priceValue: 250000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '55 sqm',
        amenities: ['King Bed', 'Dedicated Workspace', 'Executive Lounge Access', 'Meeting Table', 'Mini Bar'],
        images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop'],
        available: true,
      },
    ],
  },
  {
    id: 'eagle-point-hotel',
    name: 'Eagle Point Hotel',
    location: 'Banana Island, Lagos',
    description: 'Perched on the exclusive Banana Island, Eagle Point Hotel offers a unique island retreat with stunning water views, private beach, and world-class amenities. The ultimate escape from city life.',
    rating: 4.9,
    reviewCount: 189,
    price: '₦180,000',
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=1200&h=800&fit=crop',
    ],
    amenities: [
      'Private Beach',
      'Infinity Pool',
      'Water Sports',
      'Spa & Wellness',
      'Fine Dining',
      'Beach Bar',
      'Yacht Club',
      'Tennis Court',
      'Kids Club',
      'Helipad',
    ],
    contact: {
      phone: '+234 700 456 7890',
      email: 'stay@eaglepointhotel.com',
      address: 'Banana Island, Lagos',
    },
    rooms: [
      {
        id: 'garden-villa',
        name: 'Garden Villa',
        description: 'Private villa surrounded by lush gardens with direct beach access.',
        price: '₦180,000',
        priceValue: 180000,
        maxGuests: 3,
        bedType: 'King Bed',
        size: '80 sqm',
        amenities: ['King Bed', 'Private Terrace', 'Garden View', 'Outdoor Shower', 'Mini Bar'],
        images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'ocean-suite',
        name: 'Ocean Suite',
        description: 'Luxurious suite with panoramic ocean views and private balcony.',
        price: '₦320,000',
        priceValue: 320000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '90 sqm',
        amenities: ['King Bed', 'Ocean View', 'Private Balcony', 'Jacuzzi', 'Butler Service', 'Mini Bar'],
        images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'overwater-bungalow',
        name: 'Overwater Bungalow',
        description: 'Exclusive bungalow built over the water with glass floor panels.',
        price: '₦550,000',
        priceValue: 550000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '120 sqm',
        amenities: ['Glass Floor', 'Private Deck', 'Ocean Access', 'Outdoor Tub', 'Butler Service', 'Champagne Bar'],
        images: ['https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&h=600&fit=crop'],
        available: true,
      },
    ],
  },
  {
    id: 'transcorp-hilton',
    name: 'Transcorp Hilton Abuja',
    location: 'Central Business District, Abuja',
    description: 'Located in the heart of Abuja, Transcorp Hilton offers world-class accommodation with stunning views of the city. Perfect for business travelers seeking convenience and luxury.',
    rating: 4.7,
    reviewCount: 567,
    price: '₦110,000',
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&h=800&fit=crop',
    ],
    amenities: [
      'Free WiFi',
      'Outdoor Pool',
      'Fitness Center',
      'Multiple Restaurants',
      'Lounge & Bar',
      'Business Center',
      'Conference Facilities',
      'Spa',
      'Shopping Arcade',
      '24/7 Security',
    ],
    contact: {
      phone: '+234 700 567 8901',
      email: 'abuja@transcorphilton.com',
      address: '1 Aguiyi Ironsi Street, Maitama, Abuja',
    },
    rooms: [
      {
        id: 'guest-room',
        name: 'Guest Room',
        description: 'Comfortable room with modern amenities and city views.',
        price: '₦110,000',
        priceValue: 110000,
        maxGuests: 2,
        bedType: 'Queen Bed',
        size: '32 sqm',
        amenities: ['Queen Bed', 'Work Desk', 'Mini Bar', 'Safe', 'Flat Screen TV', 'Coffee Maker'],
        images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'executive-room',
        name: 'Executive Room',
        description: 'Spacious room with access to executive lounge and premium amenities.',
        price: '₦175,000',
        priceValue: 175000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '42 sqm',
        amenities: ['King Bed', 'Executive Lounge', 'Mini Bar', 'Safe', 'Bathrobes', 'City View'],
        images: ['https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&h=600&fit=crop'],
        available: true,
      },
    ],
  },
  {
    id: 'bonny-view-hotel',
    name: 'Bonny View Hotel',
    location: 'Port Harcourt, Rivers State',
    description: 'Experience warm hospitality in Port Harcourt at Bonny View Hotel. Our property offers comfortable accommodation with excellent facilities for business and leisure guests.',
    rating: 4.5,
    reviewCount: 234,
    price: '₦65,000',
    image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&h=800&fit=crop',
    ],
    amenities: [
      'Free WiFi',
      'Swimming Pool',
      'Fitness Center',
      'Restaurant',
      'Bar',
      'Room Service',
      'Conference Hall',
      'Parking',
      'Laundry',
      'Airport Shuttle',
    ],
    contact: {
      phone: '+234 700 678 9012',
      email: 'info@bonnyviewhotel.com',
      address: '37bonny Street, Port Harcourt',
    },
    rooms: [
      {
        id: 'standard',
        name: 'Standard Room',
        description: 'Cozy room with essential amenities for a comfortable stay.',
        price: '₦65,000',
        priceValue: 65000,
        maxGuests: 2,
        bedType: 'Double Bed',
        size: '25 sqm',
        amenities: ['Double Bed', 'TV', 'Air Conditioning', 'WiFi', 'Private Bathroom'],
        images: ['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&h=600&fit=crop'],
        available: true,
      },
      {
        id: 'deluxe',
        name: 'Deluxe Room',
        description: 'Spacious room with modern furnishings and extra amenities.',
        price: '₦95,000',
        priceValue: 95000,
        maxGuests: 2,
        bedType: 'King Bed',
        size: '35 sqm',
        amenities: ['King Bed', 'Mini Bar', 'Safe', 'Smart TV', 'Rain Shower'],
        images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop'],
        available: true,
      },
    ],
  },
]

