export const STATES = [
  'Abia',
  'Adamawa', 
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT - Abuja',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara'
] as const;

export type State = typeof STATES[number];

export const CITIES_BY_STATE: Record<State, string[]> = {
  'Abia': ['Aba', 'Umuahia', 'Umu Nneochi', 'Ohafia', 'Arochukwu'],
  'Adamawa': ['Yola', 'Mubi', 'Numan', 'Jalingo', 'Gombe'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Itu'],
  'Anambra': ['Onitsha', 'Nnewi', 'Awka', 'Ekwulobia', 'Ihiala'],
  'Bauchi': ['Bauchi', 'Tafawa Balewa', 'Misau', 'Shira'],
  'Bayelsa': ['Yenagoa', 'Amassoma', 'Nembe', 'Ogbia'],
  'Benue': ['Makurdi', 'Gboko', 'Welfare', 'Katsina-Ala'],
  'Borno': ['Maiduguri', 'Bama', 'Bi', 'Dikwa'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Obudu'],
  'Delta': ['Warri', 'Asaba', 'Sapele', 'Ughelli', 'Agbor'],
  'Ebonyi': ['Abakaliki', 'Afikpo', 'Onunwa', 'Edd'],
  'Edo': ['Benin City', 'Ekpoma', 'Auchi', 'Uromi'],
  'Ekiti': ['Ado-Ekiti', 'Ikere', 'Afikpo', 'Oye'],
  'Enugu': ['Enugu', 'Nsukka', 'Agbani', 'Awgu'],
  'FCT - Abuja': ['Abuja', 'Gwagwalada', 'Kuje', 'Kwali', 'Abaji'],
  'Gombe': ['Gombe', 'Billiri', 'Kaltungo', 'Shongom'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Mbaise'],
  'Jigawa': ['Dutse', 'Gumel', 'Hadejia', 'Kazaure'],
  'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Birnin Gwari'],
  'Kano': ['Kano', 'Dambatta', 'Kumbotso', 'Kano Municipal'],
  'Katsina': ['Katsina', 'Daura', 'Funtua', 'Kankara'],
  'Kebbi': ['Birnin Kebbi', 'Yauri', 'Jega', 'Argungu'],
  'Kogi': ['Lokoja', 'Okene', 'Ankpa', 'Anyigba'],
  'Kwara': ['Ilorin', 'Offa', 'Omu-Aran', 'Lafiagi'],
  'Lagos': ['Ikeja', 'Lagos Island', 'Badagry', 'Ikorodu', 'Epe', 'Agege', 'Surulere', 'Mushin'],
  'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Doma'],
  'Niger': ['Minna', 'Suleja', 'Bida', 'Kontagora'],
  'Ogun': ['Abeokuta', 'Ijebu-Ode', 'Ifo', 'Ota'],
  'Ondo': ['Akure', 'Ondo', 'Owo', 'Ikare-Akoko'],
  'Osun': ['Osogbo', 'Ifon', 'Ile-Ife', 'Ilesha', 'Ejigbo'],
  'Oyo': ['Ibadan', 'Oyo', 'Ogbomosho', 'Iseyin'],
  'Plateau': ['Jos', 'Pankshin', 'Langtang', 'Shendam'],
  'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Bori'],
  'Sokoto': ['Sokoto', 'Tambuwal', 'Illela', 'Goronyo'],
  'Taraba': ['Jalingo', 'Wukari', 'Takum', 'Zing'],
  'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Nguru'],
  'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka']
} as const;

